### PR TITLE
updated to work w. ss3

### PR DESCRIPTION
**Pull request by anselmdk**
I upgraded this to work with SS3.

For the sortable fields I'm using [SortableGridField](https://github.com/UndefinedOffset/SortableGridField), so that's a new dependency, but that should be beasy to take out.

Also, here's some basics on how to instantiate it in the `getCMSFields` method:

```
    $polls = Poll::get();
    $pollsMap = $polls->map('ID', 'Title');
    $fields->push($dropdown = new DropdownField('PollID', 'Poll', $pollsMap));
    $dropdown->setEmptyString('--- Select a poll ---');
```

### CODE REVIEW

**Comment by jraack** [comment]
I don't get the vote form working in my templating.
Any directions?
Great, thank you!

**Comment by mateusz** [comment]
Totally missed this one. Sorry! Looks good and thank you for your fix!

**Comment by mateusz** [comment]
@raack08 have just updated docs and retested, and seems to be working fine to me. Did you add $PollForm into your template and did you build and select the poll in the CMS?

**Comment by jraack** [comment]
Mateusz, Thx for your fast reply.

Yes i did, but i have to say that my structure is slightly different.
I have a pageholder where i loop through my children... so i want a list with multiple polls on one page.
But when i request de $PollForm i get an empty string.

best regards,
Jay.

**Comment by jraack** [comment]
ok, nm fixed that.

Only problem now is submitting the vote, old redirection in de PollForm.php i think.
Any directions?

using $this->controller->redirect(url) is the proper use in ss3

**Comment by mateusz** [comment]
Hmm did you update your code? Have fixed that in
https://github.com/mateusz/silverstripe-polls/blob/master/code/PollForm.php#L79-
the Director::redirect is deprecated and we have to use controller
instead.

Otherwise I need more info :)

On Wed, Dec 5, 2012 at 11:03 PM, raack08 notifications@github.com wrote:

> ok, nm fixed that.
> 
> Only problem now is submitting the vote, old redirection in de
> PollForm.php i think.
> Any directions?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mateusz/silverstripe-polls/pull/12#issuecomment-11035784.

## 

Mateusz Uzdowski | Developer
SilverStripe
http://silverstripe.com/

Phone: +64 4 978 7330 xtn 68
Skype: MateuszUzdowski

**Pull request merged**
