### PR TITLE
Vote abstraction

### PR DESCRIPTION
**Pull request by tomspeak**
Significant progress towards fixing #10 and #8

Simply need to create new vote_backends to allow those possibilities

### CODE REVIEW

**Comment by dhensby** [comment]
I looked into using the injector pattern but this seems difficult as the `vote_backend` requires an argument which is the instance of the current `Poll`...

If anyone knows how I can configure that via the YAML / private statics then I'll continue....

**Comment by mateusz** [comment]
Thanks for help :-)

We don't have to configure the reverse link back to Poll via the config system. I believe we can add it in by defining the setter on the Poll class:

``` php
// DI system will automatically prefer the setter over setting the $voteHandler directly
// We should be able to use it to configure the reverse dependency.
function setVoteHandler($handler) {
  $handler->setPoll($this);
  $this->voteHanlder = $handler;
}
```

(I haven't tested it but it should work)

Another solution would be to treat the Vote_Backend as a bag of helper methods, and pass in the Poll object every time you invoke a method in Poll:

``` php
public function canVote() {
  return $this->voteHandler->canVote($this);
}
```

We could then remove the boilerplate `setPoll` and `getPoll` in Vote_Backend. As long as this class remains quite simple, this should work fine.

I'm leaning towards the latter - there is no need for Vote_Backend to hold it's own state (in the form of $poll backwards reference). But it's your choice :-)

**Comment by dhensby** [comment]
@mateusz Ah, ok, the first example looks like it makes sense to me.

I don't really like the second one as it's very verbose and inelegant, also, it's likely that we may want other arguments to be passed in the future and always having `$this` as the first argument is really ugly!

**Comment by mateusz** [comment]
fine by me :-)

**Pull request closed without merging**
